### PR TITLE
Scaffold basic project structure #3

### PR DESCRIPTION
**Pull request by ivinjose**

### CODE REVIEW

**Comment by shidhincr** [comment]
@ivinjose Can you generate it using the latest `create-react-app` ?

https://github.com/facebookincubator/create-react-app/releases

**Comment by ivinjose** [comment]
@shidhincr Done. Check.

**Comment by shidhincr** [comment]
@ivinjose Did you re-generate it using the new version of `create-react-app` ?

**Comment by ivinjose** [comment]
@shidhincr Yes. But there wasn't much change in the contents.

**Comment by shidhincr** [comment]
👍

**Pull request merged**
